// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VitalSignsMonitor.Models;

#nullable disable

namespace VitalSignsMonitor.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250722074653_UpdateVitalSignsSeed")]
    partial class UpdateVitalSignsSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("VitalSignsMonitor.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 45,
                            Name = "John Doe",
                            RoomNumber = "101"
                        },
                        new
                        {
                            Id = 2,
                            Age = 32,
                            Name = "Jane Smith",
                            RoomNumber = "102"
                        },
                        new
                        {
                            Id = 3,
                            Age = 67,
                            Name = "Bob Johnson",
                            RoomNumber = "103"
                        });
                });

            modelBuilder.Entity("VitalSignsMonitor.Models.VitalSign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiastolicBP")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HeartRate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OxygenSaturation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SystolicBP")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("VitalSigns");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DiastolicBP = 80,
                            HeartRate = 80,
                            OxygenSaturation = 97,
                            PatientId = 1,
                            SystolicBP = 120,
                            Timestamp = new DateTime(2025, 7, 21, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            DiastolicBP = 85,
                            HeartRate = 95,
                            OxygenSaturation = 92,
                            PatientId = 2,
                            SystolicBP = 135,
                            Timestamp = new DateTime(2025, 7, 21, 12, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            DiastolicBP = 95,
                            HeartRate = 110,
                            OxygenSaturation = 88,
                            PatientId = 3,
                            SystolicBP = 145,
                            Timestamp = new DateTime(2025, 7, 21, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("VitalSignsMonitor.Models.VitalSign", b =>
                {
                    b.HasOne("VitalSignsMonitor.Models.Patient", "Patient")
                        .WithMany("VitalSigns")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("VitalSignsMonitor.Models.Patient", b =>
                {
                    b.Navigation("VitalSigns");
                });
#pragma warning restore 612, 618
        }
    }
}
